version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: OmniUpdate
      POSTGRES_USER: OmniUpdate
      POSTGRES_PASSWORD: OmniUpdate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
